{% set name = "pdfplumber" %}
{% set version = "0.11.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pdfplumber-{{ version }}.tar.gz
  sha256: fa67773e5e599de1624255e9b75d1409297c5e1d7493b386ce63648637c67368

build:
  number: 0
  entry_points:
    - pdfplumber = pdfplumber.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - pdfminer.six ==20240706
    - pypdfium2
    - pillow >=9.1
    - python >={{ python_min }}
    - wand >=0.6.10

test:
  imports:
    - pdfplumber
  commands:
    - pip check
    - pdfplumber --help
  requires:
    - pip
    - setuptools
    - python {{ python_min }}

about:
  home: https://github.com/jsvine/pdfplumber
  summary: Plumb a PDF for detailed information about each char, rectangle, and line.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - melonhead901
