{% set name = "pdfplumber" %}
{% set version = "0.11.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pdfplumber-{{ version }}.tar.gz
  sha256: 481224b678b2bbdbf376e2c39bf914144eef7c3d301b4a28eebf0f7f6109d6dc

build:
  entry_points:
    - pdfplumber = pdfplumber.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools <81.0
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - pdfminer.six ==20251107
    - pillow >=9.1
    - pypdfium2 >=4.18.0

test:
  imports:
    - pdfplumber
  commands:
    - pdfplumber --help
    - python -c "from importlib.metadata import version; v = version('pdfplumber'); print(v); assert v == '{{ version }}'"
  requires:
    - pip
    - setuptools
    - python {{ python_min }}

about:
  home: https://github.com/jsvine/pdfplumber
  summary: Plumb a PDF for detailed information about each char, rectangle, and line.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kellend-git
    - rxm7706
